In [135]:
# import the library
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# sklearn :: utils
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold

# sklearn :: models
from sklearn.neighbors import KNeighborsClassifier

# sklearn :: evaluation metrics
from sklearn.metrics import cohen_kappa_score

sns.set_style('whitegrid')

# Problem definition

Predict when a pet will be adopted

# Load the data

In [136]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
print(df_train.shape, df_test.shape)

(10000, 24) (4993, 23)

# Feature Engineering

In [137]:
print(df_train.columns)
df_train.head()
#df_train['Gender'].dtype

#ValueError: could not convert string to float: 'Female'
#df_train['Gender'] = df_train['Gender'].apply(str)
#print(df_train['Gender'].dtype)
#1 = Male, 2 = Female, 3 = Mixed
#df_train['Gender'] = np.where((df_train['Gender']=='1'), 'Male', df_train['Gender'])
#df_train['Gender'] = np.where((df_train['Gender']=='2'), 'Female', df_train['Gender'])
#df_train['Gender'] = np.where((df_train['Gender']=='3'), 'Mixed', df_train['Gender'])

#df_test['Gender'] = df_test['Gender'].apply(str)
#df_test['Gender'] = np.where((df_test['Gender']=='1'), 'Male', df_test['Gender'])
#df_test['Gender'] = np.where((df_test['Gender']=='2'), 'Female', df_test['Gender'])
#df_test['Gender'] = np.where((df_test['Gender']=='3'), 'Mixed', df_test['Gender'])

#print(df_train['Gender'])

#df_train['Type'] = df_train['Type'].apply(str)
#df_train['Type'] = np.where((df_train['Type']=='1'), 'Dog', df_train['Type'])
#df_train['Type'] = np.where((df_train['Type']=='2'), 'Cat', df_train['Type'])

#df_test['Type'] = df_test['Type'].apply(str)
#df_test['Type'] = np.where((df_test['Type']=='1'), 'Dog', df_test['Type'])
#df_test['Type'] = np.where((df_test['Type']=='2'), 'Cat', df_test['Type'])

#print(df_train['Type'])
#print(df_test['Type'])

Index(['Type', 'Name', 'Age', 'Breed1', 'Breed2', 'Gender', 'Color1', 'Color2',
       'Color3', 'MaturitySize', 'FurLength', 'Vaccinated', 'Dewormed',
       'Sterilized', 'Health', 'Quantity', 'Fee', 'State', 'RescuerID',
       'VideoAmt', 'Description', 'PetID', 'PhotoAmt', 'AdoptionSpeed'],
      dtype='object')

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,1,â¥â¥â¥ Lily â¥â¥â¥,36,307,0,2,2,7,0,2,...,1,1,0,41326,337914b09c2fa5460e195197e994ef98,0,Adorable 3 year old Lily looking for a forever...,3f8824a3b,1.0,4
1,2,Cookie,3,266,0,1,6,7,0,2,...,1,1,0,41327,4bb1ebb92158078ad54a6bb23c10dffc,0,i rescue this stary kitten from market near my...,9238eb7fc,1.0,2
2,2,Favour Speedy Abundance And Courage,7,250,252,1,1,2,0,2,...,1,4,0,41327,99ba8ce53b4d8515e417e7921563d923,0,The mother was a Burmese cross and had since p...,f0a1f2b90,2.0,4
3,1,NaN,3,307,0,1,2,0,0,3,...,1,1,0,41327,3f3ef74c486beba3bc87f6dbaee772bf,0,This puppy is: 1. Male 2. 3 months old 3. Brow...,7d028bdea,4.0,2
4,2,Abandoned Kitty,1,266,0,1,1,6,7,1,...,1,1,0,41401,844f03ab8054007d4be6686f3a9702b9,0,Mother cat gave birth to a litter of 3 and too...,8377bfe97,0.0,2

In [138]:
# Check for missing values
#df_train.isnull().sum(axis = 0)

df_test.isnull().sum(axis = 0)

Type              0
Name            415
Age               0
Breed1            0
Breed2            0
Gender            0
Color1            0
Color2            0
Color3            0
MaturitySize      0
FurLength         0
Vaccinated        0
Dewormed          0
Sterilized        0
Health            0
Quantity          0
Fee               0
State             0
RescuerID         0
VideoAmt          0
Description       4
PetID             0
PhotoAmt          0
dtype: int64

In [139]:
# Validate column size
col = 'Type'
[print(str(col)+'_'+str(c)) for c in df_dummies.columns]

df_dummies = pd.get_dummies(df_train[col])
print(df_dummies)

Type_Vaccinated_1
Type_Vaccinated_2
Type_Vaccinated_3
      1  2
0     1  0
1     0  1
2     0  1
3     1  0
4     0  1
5     1  0
6     1  0
7     1  0
8     0  1
9     1  0
10    0  1
11    1  0
12    1  0
13    1  0
14    0  1
15    0  1
16    0  1
17    1  0
18    0  1
19    1  0
20    0  1
21    0  1
22    1  0
23    1  0
24    0  1
25    0  1
26    0  1
27    1  0
28    0  1
29    0  1
...  .. ..
9970  0  1
9971  0  1
9972  0  1
9973  1  0
9974  0  1
9975  0  1
9976  0  1
9977  0  1
9978  0  1
9979  1  0
9980  1  0
9981  1  0
9982  0  1
9983  1  0
9984  0  1
9985  0  1
9986  0  1
9987  0  1
9988  0  1
9989  1  0
9990  1  0
9991  1  0
9992  0  1
9993  0  1
9994  0  1
9995  1  0
9996  1  0
9997  0  1
9998  1  0
9999  0  1

[10000 rows x 2 columns]

In [140]:
# apply dummies on the training set
col = 'Health'
df_dummies = pd.get_dummies(df_train[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_train = pd.concat([df_train, df_dummies], axis=1)

# apply the same dummies on the test set
col = 'Health'
df_dummies = pd.get_dummies(df_test[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_test = pd.concat([df_test, df_dummies], axis=1)


# apply dummies on the training set
col = 'Gender'
df_dummies = pd.get_dummies(df_train[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_train = pd.concat([df_train, df_dummies], axis=1)

# apply the same dummies on the test set
col = 'Gender'
df_dummies = pd.get_dummies(df_test[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_test = pd.concat([df_test, df_dummies], axis=1)

#df_Gender = pd.get_dummies(df_train['Gender'])
#df_train = pd.concat([df_train, df_Gender], axis=1)

#df_Gender = pd.get_dummies(df_test['Gender'])
#df_test = pd.concat([df_test, df_Gender], axis=1)



# apply dummies on the training set
col = 'Type'
df_dummies = pd.get_dummies(df_train[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_train = pd.concat([df_train, df_dummies], axis=1)

# apply the same dummies on the test set
col = 'Type'
df_dummies = pd.get_dummies(df_test[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_test = pd.concat([df_test, df_dummies], axis=1)

#df_Type = pd.get_dummies(df_train['Type'])
#df_train = pd.concat([df_train, df_Type], axis=1)

#df_Type = pd.get_dummies(df_test['Type'])
#df_test = pd.concat([df_test, df_Type], axis=1)




# apply dummies on the training set
col = 'MaturitySize'
df_dummies = pd.get_dummies(df_train[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_train = pd.concat([df_train, df_dummies], axis=1)

# apply the same dummies on the test set
col = 'MaturitySize'
df_dummies = pd.get_dummies(df_test[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_test = pd.concat([df_test, df_dummies], axis=1)

# apply dummies on the training set
col = 'Vaccinated'
df_dummies = pd.get_dummies(df_train[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_train = pd.concat([df_train, df_dummies], axis=1)

# apply the same dummies on the test set
col = 'Vaccinated'
df_dummies = pd.get_dummies(df_test[col])
df_dummies.columns = [str(col)+'_'+str(c) for c in df_dummies.columns]
df_test = pd.concat([df_test, df_dummies], axis=1)




#df_Sterilized = pd.get_dummies(df_train['Sterilized'])
#df_train = pd.concat([df_train, df_Sterilized], axis=1)

#df_Sterilized = pd.get_dummies(df_test['Sterilized'])
#df_test = pd.concat([df_test, df_Sterilized], axis=1)

#df_State = pd.get_dummies(df_train['State'])
#df_train = pd.concat([df_train, df_State], axis=1)

#df_State = pd.get_dummies(df_test['State'])
#df_test = pd.concat([df_test, df_State], axis=1)

#df_Dewormed = pd.get_dummies(df_train['Dewormed'])
#df_train = pd.concat([df_train, df_Sterilized], axis=1)

#df_Dewormed = pd.get_dummies(df_test['Dewormed'])
#df_test = pd.concat([df_test, df_Sterilized], axis=1)


df_Breed1 = pd.get_dummies(df_train['Breed1'])
df_train = pd.concat([df_train, df_Breed1], axis=1)

df_Breed1 = pd.get_dummies(df_test['Breed1'])
df_test = pd.concat([df_test, df_Breed1], axis=1)


df_Breed2 = pd.get_dummies(df_train['Breed2'])
df_train = pd.concat([df_train, df_Breed2], axis=1)

df_Breed2 = pd.get_dummies(df_test['Breed2'])
df_test = pd.concat([df_test, df_Breed2], axis=1)


#df_Color1 = pd.get_dummies(df_train['Color1'])
#df_train = pd.concat([df_train, df_Color1], axis=1)

#df_Color1 = pd.get_dummies(df_test['Color1'])
#df_test = pd.concat([df_test, df_Color1], axis=1)

#df_Color2 = pd.get_dummies(df_train['Color2'])
#df_train = pd.concat([df_train, df_Color2], axis=1)

#df_Color2 = pd.get_dummies(df_test['Color2'])
#df_test = pd.concat([df_test, df_Color2], axis=1)

#df_Color3 = pd.get_dummies(df_train['Color3'])
#df_train = pd.concat([df_train, df_Color3], axis=1)

#df_Color3 = pd.get_dummies(df_test['Color3'])
#df_test = pd.concat([df_test, df_Color3], axis=1)

In [141]:
print(df_train.columns)
print(df_train['Health'])
print(df_train['Gender'])

Index([        'Type',         'Name',          'Age',       'Breed1',
             'Breed2',       'Gender',       'Color1',       'Color2',
             'Color3', 'MaturitySize',
       ...
                  294,            295,            296,            299,
                  300,            303,            304,            305,
                  306,            307],
      dtype='object', length=322)
0       1
1       1
2       1
3       1
4       1
5       1
6       1
7       1
8       2
9       1
10      1
11      1
12      1
13      1
14      1
15      1
16      1
17      1
18      1
19      1
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      2
29      1
       ..
9970    1
9971    1
9972    1
9973    1
9974    1
9975    1
9976    1
9977    1
9978    1
9979    2
9980    1
9981    1
9982    1
9983    1
9984    1
9985    1
9986    1
9987    1
9988    1
9989    1
9990    1
9991    1
9992    1
9993    1
9994    1
9995    1
9996    2
9997    1
9998    1
9999    1
Name: Health, Length: 10000, dtype: int64
0       2
1       1
2       1
3       1
4       1
5       1
6       2
7       2
8       2
9       1
10      3
11      2
12      1
13      1
14      1
15      3
16      2
17      1
18      3
19      1
20      2
21      2
22      2
23      2
24      2
25      3
26      1
27      2
28      2
29      1
       ..
9970    1
9971    2
9972    2
9973    1
9974    3
9975    3
9976    2
9977    2
9978    1
9979    1
9980    1
9981    3
9982    1
9983    1
9984    1
9985    2
9986    3
9987    2
9988    2
9989    1
9990    1
9991    2
9992    1
9993    2
9994    1
9995    2
9996    2
9997    2
9998    1
9999    2
Name: Gender, Length: 10000, dtype: int64

In [142]:
# select the columns
#X_columns = ['Age', 'Fee', 'Health_1', 'Health_2', 'Health_3']
X_columns = ['Age', 'Fee', 'Health_1', 'Health_2', 'Health_3'
             #,'Gender_1','Gender_2', 'Gender_3'
             ,'Gender'
             #,'Type_1','Type_2'
             ,'Type'
             , 'MaturitySize_1','MaturitySize_2', 'MaturitySize_3', 'MaturitySize_4'
             ,'Breed1','Breed2'
             #,'Color1','Color2','Color3'
             #,'Quantity' 
             ,'Vaccinated_1','Vaccinated_2', 'Vaccinated_3'
             #,'Dewormed'
             #,'State'
             #,'Sterilized'
            ] #+ list(df_Gender.columns)

y_column = ['AdoptionSpeed']

# Model Training

In [143]:
# split the data using sklearn

threshold = 0.8
X = df_train[X_columns]
y = df_train[y_column]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1.0-threshold, shuffle=True)

print('X_train', X_train.shape)
print('y_train', y_train.shape)
print('X_test', X_test.shape)
print('y_test', y_test.shape)

X_train (8000, 16)
y_train (8000, 1)
X_test (2000, 16)
y_test (2000, 1)

In [144]:
# train a KNN Classifier
model = KNeighborsClassifier()
model.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)

# Model Evaluation

In [145]:
kappa = cohen_kappa_score(y_test, y_pred, weights ='quadratic')
print('kappa', round(kappa, 4))
print(confusion_matrix(y_test, y_pred))

kappa 0.261
[[  3  19  23   9   4]
 [  7 148 153  59  47]
 [  7 138 218  86  82]
 [ 13  89 147  85  86]
 [ 11  90 153  85 238]]

Using Cross Validation

In [146]:
k = 10
results = []
kf = KFold(n_splits=k)
for train_index, test_index in kf.split(X):
    X_train, X_test = X.values[train_index], X.values[test_index]
    y_train, y_test = y.values[train_index], y.values[test_index]
    model.fit(X_train, y_train.ravel())
    y_pred = model.predict(X_test)
    kappa = cohen_kappa_score(y_test, y_pred, weights ='quadratic')
    results.append(round(kappa, 4))

print('Kappa for each fold:', results)
print('AVG(kappa)', round(np.mean(results), 4))
print('STD(kappa)', round(np.std(results), 4))

Kappa for each fold: [0.2532, 0.2396, 0.207, 0.2016, 0.2337, 0.2009, 0.1786, 0.2369, 0.2448, 0.1889]
AVG(kappa) 0.2185
STD(kappa) 0.0247

# Prepare your submission

In [147]:
df_prediction = df_test[X_columns]
df_test['AdoptionSpeed'] = model.predict(df_prediction)
df_test[['PetID', 'AdoptionSpeed']]

          PetID  AdoptionSpeed
0     f42161740              1
1     0118db3a8              4
2     e5164d828              2
3     5335bfb38              2
4     ff2cf88a0              4
5     1d13441b9              2
6     7d835cf7c              2
7     577d15fea              3
8     91736f444              3
9     db194aec8              4
10    10516f3c6              4
11    c3106dcd5              3
12    fc3fbbb99              4
13    42dd3f3ff              2
14    da3be5cb2              3
15    4e9a13862              1
16    2fbf2cb7c              3
17    f45457bdc              4
18    aad08c47b              2
19    181d40c5e              3
20    1a3c44785              4
21    6786609aa              2
22    1c67c5f4c              2
23    bf6a56d33              2
24    06fda20a2              2
25    b940cf8b8              2
26    239c4b696              3
27    b67a29908              1
28    72f092b4b              1
29    7d1d7a4f6              2
...         ...            ...
4963  ed0185e39              4
4964  bf90589d1              4
4965  0f796d3f9              4
4966  6d53b2d19              1
4967  7bc54baef              1
4968  87615b2c6              4
4969  6f07e7abf              2
4970  3bf6cdab0              1
4971  00ac364a4              2
4972  578b82f50              3
4973  f24991ef7              1
4974  2e9a64836              4
4975  3dab3050c              4
4976  4f6029457              2
4977  b23e29c89              1
4978  0c46298f8              4
4979  2f6cde44b              4
4980  2f3677597              4
4981  256f40704              2
4982  653f94080              1
4983  878e36da4              3
4984  46cf6356e              2
4985  ef50eab33              3
4986  a40116bf1              3
4987  7ed14130d              2
4988  3b2b69d20              2
4989  360215e23              3
4990  0c612e8df              4
4991  9b1241ef0              4
4992  ffe7f0b70              4

[4993 rows x 2 columns]

In [148]:
df_test[['PetID', 'AdoptionSpeed']].to_csv('submission_knn.csv', index=False)